---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-bucket
spec:
  template:
    spec:
      containers:
        - name: create-bucket
          image: oci.stackable.tech/sdp/tools:1.0.0-stackable0.0.0-dev
          command:
            - bash
            - -xeuo
            - pipefail
            - -c
            - |
              # Create the S3 bucket using the RustFS API
              export RUSTFS_ACCESS_KEY=$(cat /rustfs-secret/RUSTFS_ACCESS_KEY)
              export RUSTFS_SECRET_KEY=$(cat /rustfs-secret/RUSTFS_SECRET_KEY)
              export RUSTFS_ENDPOINT=http://rustfs-svc:9000
              export RUSTFS_BUCKET=demo

              # Install MinIO client
              ARCH=$(arch)
              if [ "$ARCH" = "x86_64" ]; then
                BINARCH="linux-amd64"
              elif [ "$ARCH" = "aarch64" ]; then
                BINARCH="linux-arm64"
              else
                echo "Unsupported architecture: $ARCH"
                exit 1
              fi
              curl https://dl.min.io/client/mc/release/${BINARCH}/mc -o mc
              chmod 755 mc

              # Configure mc and create the bucket with public rw access
              mc alias set rustfs ${RUSTFS_ENDPOINT} ${RUSTFS_ACCESS_KEY} ${RUSTFS_SECRET_KEY}
              mc mb rustfs/${RUSTFS_BUCKET}
              mc anonymous set public rustfs/${RUSTFS_BUCKET}
          volumeMounts:
            - name: rustfs-secret
              mountPath: /rustfs-secret
      volumes:
        - name: rustfs-secret
          secret:
            secretName: rustfs-secret
      restartPolicy: OnFailure
  backoffLimit: 50
